version: '3.9'

services:
  app:
    build: .
    container_name: durdon_app
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@learning_db:5432/durdon_bot?schema=public
    env_file:
      - .env
    ports:
      - "3001:3000"
    volumes:
      - /var/data/learning_app_new/uploads_dev:/app/uploads
    networks:
      - app_network

networks:
  app_network:
    external: true
    name: default
