version: "3.9"

services:
  db:
    image: postgres:16
    container_name: learning_databse
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: imtihon_5oy
    ports:
      - "5436:5432"
    volumes:
      - baza_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: payment_redis 
    restart: always 
    ports:
      - "6381:6379"
  app:
    build: .
    container_name: educoin_payment_app
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        pnpm run start:prod
      "
    environment:
      DATABASE_URL: postgres://postgres:12345@db:5432/imtihon_5oy
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  baza_data:
